name: Publish win-x64

on: [push]

jobs:
  Dotnet-Publish:
    runs-on: ubuntu-latest
    steps:
      run: dotnet publish Program -c Release -r win7-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true -p:PublishReadyToRun=false
  