name: Publish win-x64

on: [push]

jobs:
  Dotnet-Publish:
    runs-on: ubuntu-latest
    steps:
    - run: dotnet publish Program/Program.csproj -c Release -p:PublishSingleFile=true -p:PublishTrimmed=true -p:PublishReadyToRun=false
  